class: App\LabImage
icon: fa fa-flask
sort:
  field: id
  order: asc
list:
  id: ID
  title: Título
fields:
  image:
    label: Imagen
    type: image
    validate: required|image
    validateAtEdit: image
    path: storage/lab
    sizes:
      - resize: 1200
        suffix: n
        format: png
      - fit: 640x640
        suffix: t
  title:
    label: Título
    type: text
    validate: required
  offset:
    label: Desfase
    type: text
  size:
    label: Tamaño
    type: select
    options:
      0: 1⨉1
      1: 1⨉2
      2: 2⨉1
      3: 2⨉2
