class: App\ProjectImage
icon: fa fa-picture-o
hidden: true
child: images
sort:
  field: created_at
  order: desc
list:
  id: ID
  title: Título
  created_at: Fecha
fields:
  image:
    label: Imagen
    type: image
    validate: required|image
    validateAtEdit: image
    path: storage/project_images
    sizes:
      - resize: 1980
        suffix: n
      - fit: 640x640
        suffix: t
  title:
    label: Título
    type: text
    validate: required
  link:
    label: Enlace
    type: text
    validate: url
  size:
    label: Tamaño
    type: select
    options:
      0: 1⨉1
      1: 1⨉2
      2: 2⨉1
      3: 2⨉2
