class: App\Project
icon: fa fa-folder-open
children:
  - ProjectImage
slug:
  field: name
  column: url
sort:
  field: name
  order: asc
list:
  id: ID
  name: Nombre
  category:name: Categoría
  panel_link!:
fields:
  image:
    label: Imagen
    type: image
    validate: required|image
    validateAtEdit: image
    path: storage/projects
    sizes:
      - resize: 1200
        suffix: n
      - resize: 2400
        suffix: f
      - fit: 640x640
        suffix: t
  name:
    label: Nombre
    type: text
    validate: required
  subtitle:
    label: Subtítulo
    type: text
  link:
    label: Enlace
    type: text
    validate: url
    placeholder: http://...
  client:
    label: Cliente
    type: text
  duration:
    label: Duración
    type: text
  materials:
    label: Materiales
    type: text
  finish:
    label: Acabados
    type: text
  project_category_id:
    label: Categoría
    type: select
    options: App\ProjectCategory
  description:
    label: Descripción
    type: textarea
    validate: required
  credits:
    label: Créditos
    type: textarea
  size:
    label: Tamaño
    type: select
    options:
      0: 1⨉1
      1: 1⨉2
      2: 2⨉1
      3: 2⨉2
